import esbuild from 'esbuild';
import path from 'node:path';
import process from 'process';
import { fileURLToPath } from 'node:url';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const nodeBuiltinExternals = builtinModules.filter(
	(moduleName) => moduleName !== 'crypto' && moduleName !== 'node:crypto',
);

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	alias: {
		crypto: path.resolve(__dirname, 'crypto-shim.cjs'),
	},
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...nodeBuiltinExternals,
	],
	format: 'cjs',
	target: 'es2021',
	mainFields: ['browser', 'module', 'main'],
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
